import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { AnalyticsEventType } from '@prisma/client';
import {
  IsEnum,
  IsIn,
  IsInt,
  IsNotEmpty,
  IsString,
  Max,
  MaxLength,
  Min,
  ValidateIf,
} from 'class-validator';

export const ANALYTICS_PROGRESS_MILESTONES = [25, 50, 75, 90] as const;
export const ANALYTICS_SESSION_ID_MAX_LENGTH = 128;
export const ANALYTICS_MAX_DURATION_SECONDS = 24 * 60 * 60;

export class RecordAnalyticsEventDto {
  @ApiProperty({
    enum: AnalyticsEventType,
    example: AnalyticsEventType.ARTICLE_VIEW,
  })
  @IsEnum(AnalyticsEventType)
  event!: AnalyticsEventType;

  @ApiProperty({
    description: 'Opaque Sanity article document id',
    example: 'sanity-document-id',
  })
  @IsString()
  @IsNotEmpty()
  articleId!: string;

  @ApiProperty({
    description:
      'Opaque anonymous analytics session id generated by the frontend',
    example: 'generated-session-id',
  })
  @IsString()
  @IsNotEmpty()
  @MaxLength(ANALYTICS_SESSION_ID_MAX_LENGTH)
  sessionId!: string;

  @ApiPropertyOptional({
    description:
      'Reading progress milestone. Required only when event is ARTICLE_PROGRESS.',
    enum: ANALYTICS_PROGRESS_MILESTONES,
    example: 50,
  })
  @ValidateIf(
    (dto: RecordAnalyticsEventDto) =>
      dto.event === AnalyticsEventType.ARTICLE_PROGRESS,
  )
  @IsIn(ANALYTICS_PROGRESS_MILESTONES)
  progress?: number;

  @ApiPropertyOptional({
    description:
      'Active reading duration in seconds. Required only when event is ARTICLE_READ.',
    example: 248,
    minimum: 0,
    maximum: ANALYTICS_MAX_DURATION_SECONDS,
  })
  @ValidateIf(
    (dto: RecordAnalyticsEventDto) =>
      dto.event === AnalyticsEventType.ARTICLE_READ,
  )
  @IsInt()
  @Min(0)
  @Max(ANALYTICS_MAX_DURATION_SECONDS)
  duration?: number;

  @ApiPropertyOptional({
    description:
      'Maximum reading progress percentage observed by the frontend. Required only when event is ARTICLE_READ.',
    example: 87,
    minimum: 0,
    maximum: 100,
  })
  @ValidateIf(
    (dto: RecordAnalyticsEventDto) =>
      dto.event === AnalyticsEventType.ARTICLE_READ,
  )
  @IsInt()
  @Min(0)
  @Max(100)
  maxProgress?: number;
}
